name: Build and Release RPM

on:
  push:
    branches:
      - create-tag-name-0513
    schedule:
      - cron: '* 5 * * *'



jobs:
  Build-rpm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: create-tag-name-0513
      - name: run scripts
        id: set_value
        run: |
          # mkdir /tmp/release
          git config --global user.name "zhangbaowen"
          git config --global user.email "zhangbaowen@hashdata.cn"
          pwd
          ls -al
          source script/update_tag_number.sh
          echo "CBDB主版本号是 $main_version"
          echo "新tag是 $new_tag"
          source script/build_cbdb_env.sh
#         wget -q https://public-artifacts.obs.cn-north-4.myhuaweicloud.com/cbdb-rpm/cloudberrydb-1.0.2-1.x86_64.rpm
          echo "::set-output name=NEW_TAG::${new_tag}"
          echo "::set-output name=MAIN_VERSION::${main_version}"

          git clone git@github.com:cloudberrydb/cloudberrydb.git
          cd cloudberrydb
          ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/home/gpadmin/cbdb-install
          make -j16
          make install
          pwd
          ruby -v
          fpm --version
          echo "制作rpm包"
          mkdir -p tmp/usr/local/cloudberrydb
          sudo cp -a /home/gpadmin/cbdb-install/* tmp/usr/local/cloudberrydb
          fpm -s dir -t rpm -n cloudberrydb -v $(echo $main_version | sed 's/^v//') -p ./ -C tmp
          pwd
          ls -al
          cp cloudberrydb-$(echo $main_version | sed 's/^v//')-1.x86_64.rpm /tmp/release




      - name: DEBUG
        run: |
          echo "${{ steps.set_value.outputs.NEW_TAG }}"
          echo "${{ steps.set_value.outputs.MAIN_VERSION }}"
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "/tmp/release/cloudberrydb-${{ steps.set_value.outputs.MAIN_VERSION#v }}-1.x86_64.rpm"
          tag_name: "${{ steps.set_value.outputs.NEW_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#          source script/build_cbdb_env.sh
#          echo "CBDB主版本号是 $main_version"
#          echo "新tag是 $new_tag"
#          git clone git@github.com:cloudberrydb/cloudberrydb.git
#          cd cloudberrydb
#          ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/home/gpadmin/cbdb-install
#          make -j16
#          make install
#          pwd
#          ruby -v
#          fpm --version
#          echo "制作rpm包"
#          mkdir -p tmp/usr/local/cloudberrydb
#          sudo cp -a /home/gpadmin/cbdb-install/* tmp/usr/local/cloudberrydb
#          fpm -s dir -t rpm -n cloudberrydb -v 1.5.2 -p ./ -C tmp
#          pwd
#          ls -al
#          cp cloudberrydb-1.5.2-1.x86_64.rpm /tmp/release



#      - name: Upload artifact
#        id: upload_artifact
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: cloudberrydb-1.0.2-1.x86_64.rpm
#          path: /tmp/release/

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#          tag_name: $new_tag
#          release_name: Release $new_tag
#          body: New release of cbdb RPM package
#          draft: false
#          prerelease: true
#
#
#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: /tmp/release/cloudberrydb-1.0.2-1.x86_64.rpm
#          asset_name: cloudberrydb-1.0.2-1.x86_64.rpm
#          asset_content_type: application/x-rpm



