name: Build CBDB RPMS
on:
  push:
#permissions:
#  id-token: write
#  contents: write

jobs:
  Build-rpm:
    runs-on: [self-hosted, Centos7]
    steps:
      - uses: actions/checkout@v3
      - name: run scripts
        run: |
          wget https://public-artifacts.obs.myhuaweicloud.com/2024-04-28script/script.tar.gz
          tar -xvf script.tar.gz
          git config --global user.name "zhangbaowen"
          git config --global user.email "zhangbaowen@hashdata.cn"
          pwd
          ls -l
          source script/build_cbdb_env.sh
          git clone git@github.com:cloudberrydb/cloudberrydb.git
          cd cloudberrydb
          ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/home/gpadmin/cbdb-install
          make -j16
          make install
          pwd
          ruby -v
          fpm --version
          echo "制作rpm包"
          mkdir -p tmp/usr/local/cloudberrydb
          sudo cp -a /home/gpadmin/cbdb-install/* tmp/usr/local/cloudberrydb
          fpm -s dir -t rpm -n cloudberrydb -v 1.5.2 -p ./ -C tmp
          pwd
          ls -al
#          echo "开始上传rpm包"
#          export PYTHONWARNINGS="ignore:Unverified HTTPS request"
#          aws s3 cp "/home/gpadmin/actions-runner/zbw-2/zbw-test-actions/zbw-test-actions/cloudberrydb/cloudberrydb-1.5.2-1.x86_64.rpm" \
#          s3://public-artifacts/cbdb-rpm/cloudberrydb-1.5.2-`date +%Y_%m_%d-%H_%M_%S`.el7.x86_64.rpm \
#          --endpoint-url 'https://obs.cn-north-4.myhuaweicloud.com' \
#          --no-progress --no-verify-ssl