name: Build and Release RPM

on:
  push:
    branches:
      - schedule-cbdb-nightly
    schedule:
      - cron: '* 5 * * *'



#env:
#  NEW_TAG=$new_tag
#  VERSION=$main_version
    # VERSION 和 NEW_TAG变量调用于script/update_tag_number.sh
    # version 指的是主版本号 eg: v1.5.2
    # new_tag 指的是新生成的整个tag eg:  v1.5.2.62-nightly

jobs:
  Build-rpm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: schedule-cbdb-nightly
      - name: run scripts
        run: |
          # mkdir /tmp/release
          git config --global user.name "zhangbaowen"
          git config --global user.email "zhangbaowen@hashdata.cn"
          pwd
          ls -al
          source script/update_tag_number.sh
          source script/build_cbdb_env.sh
          echo "CBDB主版本号是 $main_version"
          echo "新tag是 $new_tag"
          git clone git@github.com:cloudberrydb/cloudberrydb.git
          cd cloudberrydb
          ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/home/gpadmin/cbdb-install
          make -j16
          make install
          pwd
          ruby -v
          fpm --version
          echo "制作rpm包"
          mkdir -p tmp/usr/local/cloudberrydb
          sudo cp -a /home/gpadmin/cbdb-install/* tmp/usr/local/cloudberrydb
          fpm -s dir -t rpm -n cloudberrydb -v 1.5.2 -p ./ -C tmp
          pwd
          ls -al
          cp cloudberrydb-1.5.2-1.x86_64.rpm /tmp/release



#      - name: Upload artifact
#        id: upload_artifact
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: cloudberrydb-1.0.2-1.x86_64.rpm
#          path: /tmp/release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: $new_tag
          release_name: Release $new_tag
          body: New release of cbdb RPM package
          draft: false
          prerelease: true


      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "/tmp/release/cloudberrydb-1.5.2-1.x86_64.rpm"
          tag_name: v1.5.2.${{ github.run_number }}-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


