name: Build CBDB RPMS
on:
  push:
permissions:
  id-token: write
  contents: write

jobs:
  Build-rpm:
    runs-on: [self-hosted, Centos7]
    steps: |
      - name: run scripts
        run: |
          - wget https://public-artifacts.obs.myhuaweicloud.com/2024-04-28script/script.tar.gz
          - tar -xvf script.tar.gz
          - git config --global user.name "zhangbaowen"
          - git config --global user.email "zhangbaowen@hashdata.cn"
          - pwd
          - ls -l
          - source script/build_cbdb_env.sh
          - git clone git@github.com:cloudberrydb/cloudberrydb.git
          - cd cloudberrydb
          - ./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/home/gpadmin/cbdb-install
          - make -j16
          - make install
          - pwd
          - ruby -v
          - fpm --version
