name: Build CBDB RPMS
on:
  schedule:
    - cron: "12 11 * * *"


jobs:
  Build-rpm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: run scripts
        run: |
          wget https://public-artifacts.obs.myhuaweicloud.com/2024-04-28script/script.tar.gz
          echo "successfully"