name: My Workflow with Retry

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build --file Dockerfile --tag my-image:${{ github.sha }} .
        docker push my-image:${{ github.sha }}
      retry:
        max_attempts: 3 # 设置最大重试次数为3次
        delay: 5s # 设置每次重试之间的延迟时间为5秒