name: Build and Release RPM

variable:
  timestamp=$(date +"%Y%m%d%H%M%S")

on:
  push:
    branches:
      - release-cbdb-nightly

jobs:
  build_and_release:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build RPM package
        run: |
          # 在/tmp/release目录下构建cbdb-1.5.2.rpm包
          # 这里假设您已经有构建RPM包的脚本或命令
          # 示例命令：rpmbuild -bb your_spec_file.spec
          mkdir -p /tmp/release
          # 假设构建后的RPM包为cbdb-1.5.2.rpm

          wget https://public-artifacts.obs.myhuaweicloud.com/cloudberrydb-1.0.2-1.x86_64.rpm
          cp cloudberrydb-1.0.2-1.x86_64.rpm /tmp/release

#      - name: Upload artifact
#        id: upload_artifact
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: cloudberrydb-1.0.2-1.x86_64.rpm
#          path: /tmp/release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v1.5.2.${{ github.run_number }}-nightly
          release_name: Release v1.5.2-${{ github.run_number }}
          body: New release of cbdb RPM package
          draft: false
          prerelease: true

      - name: print tags
        run: |
          git tag
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "/tmp/release/cloudberrydb-1.0.2-1.x86_64.rpm"
          tag_name: v1.5.2-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


